Repository Tisn/tisn.app, pull requests merged in 2020-10, with the labels that each got.

#309 Revamped about page with images
  client/public/locales/en/translation.json
  client/public/locales/es/translation.json
  client/src/Components/About/About.js
  client/src/Components/Style/Style.js
  client/src/Components/SvgImage/SvgImage.js
  client/src/assets/images/events-dark.svg
  client/src/assets/images/events-light.svg
  client/src/assets/images/interests-dark.svg
  client/src/assets/images/interests-light.svg
  client/src/assets/images/openSource-dark.svg
  client/src/assets/images/openSource-light.svg
  client/src/assets/images/users-dark.svg
  client/src/assets/images/users-light.svg
Labels: design, enhancement, front end

#312 Populate the development database with dummy users
  api/db/populate-interests.js
  api/db/populate-users.js
  api/package-lock.json
  api/package.json
Labels: Back end, dependencies, enhancement

#318 Fix lint-staged's configuration
  api/package.json
  client/package.json
  client/src/assets/images/events.svg
  client/src/assets/images/interests.svg
  client/src/assets/images/openSource.svg
  client/src/assets/images/users.svg
Labels: bug, dependencies

#316 Update API's README to acknowledge `populate-users` script
  api/README.md
  api/db/populate-users.js
Labels: Back end, documentation

#320 Add database population master script
  README.md
  api/README.md
  api/db/db-connection.js
  api/db/drop.js
  api/db/populate-interests.js
  api/db/populate-users.js
  api/db/populate.js
  api/package-lock.json
  api/package.json
Labels: Back end, dependencies, documentation, enhancement

#326 Update some `.env-template` default values
  README.md
  api/.env-template
Labels: Back end, documentation

#327 Take into account that JS enumerates months from 0 to 11
  api/db/populate-users.js
Labels: Back end, bug

#328 Use the new `db/connection` file on the `app.js` file too
  api/app.js
  api/db/connection.js
  api/db/db-connection.js
  api/db/drop.js
  api/db/populate.js
Labels: Back end, enhancement, refactor

#329 Add script to populate (and drop) the events collection
  api/README.md
  api/db/drop.js
  api/db/populate-events.js
  api/db/populate-interests.js
  api/db/populate-users.js
  api/db/populate.js
  api/db/utils.js
  api/package-lock.json
  api/package.json
Labels: Back end, dependencies, documentation, enhancement

#330 Add `.vscode` folder with workspace configuration
  .vscode/extensions.json
  .vscode/settings.json
Labels: documentation

#331 Add script to populate attendants collection
  api/db/populate-attendants.js
  api/db/populate-events.js
  api/db/populate-users.js
  api/db/populate.js
  api/db/utils.js
Labels: Back end, enhancement

#337 Implement single origin validation through CORS
  api/app.js
Labels: Back end, security

#334 Implement database backup mechanism
  .gitignore
  api/.gitignore
  api/app.js
  api/db/backup.js
  api/db/connection.js
  api/db/dumps/.gitkeep
  api/package-lock.json
  api/package.json
  api/uploads/.gitkeep
  api/utils/cron.js
  api/utils/emails.js
Labels: Back end, dependencies, enhancement, high priority, security

#335 Add scripts to populate and drop the friendships collection
  api/db/drop.js
  api/db/populate-attendants.js
  api/db/populate-events.js
  api/db/populate-friendships.js
  api/db/populate-users.js
  api/db/populate.js
Labels: Back end, enhancement

#338 Scripts to populate and drop comments collections
  api/db/drop.js
  api/db/populate-comments.js
  api/db/populate-events.js
  api/db/populate.js
Labels: Back end, enhancement

#336 Fix for incorrect dob format #311
  client/src/logic/date-time.js
Labels: bug, front end

#344 Add scripts to populate and drop the messages collection
  api/README.md
  api/db/drop.js
  api/db/populate-comments.js
  api/db/populate-events.js
  api/db/populate-messages.js
  api/db/populate-users.js
  api/db/populate.js
  api/db/utils.js
Labels: Back end, documentation, enhancement

#345 Fix typo in the README
  README.md
Labels: documentation, enhancement

#343 Add --oplog parameter to mongodump
  api/db/backup.js
  api/package-lock.json
  api/package.json
Labels: Back end, dependencies, enhancement, high priority, security

#347 Populate (and drop) the notifications collection
  api/db/drop.js
  api/db/populate-attendants.js
  api/db/populate-comments.js
  api/db/populate-events.js
  api/db/populate-friendships.js
  api/db/populate-messages.js
  api/db/populate-notifications.js
  api/db/populate-users.js
Labels: back end, enhancement
